language: c

os:
  - osx
  - linux

compiler:
  - clang
  - gcc

env:
  matrix:
     - TOX_ENV=lint
     - TOX_ENV=py26
     - TOX_ENV=py27
     - TOX_ENV=pypy
     - TOX_ENV=docs
     - TOX_ENV=docs-spellcheck
     - TOX_ENV=docs-linkcheck
     - MACAPP_ENV=system

matrix:
  allow_failures:
    - env: TOX_ENV=docs-linkcheck
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang
    # don't build mac app on linux
    - os: linux
      env: MACAPP_ENV=system
    - os: osx
      env: TOX_ENV=lint
    - os: osx
      env: TOX_ENV=docs
    - os: osx
      env: TOX_ENV=docs-spellcheck
    - os: osx
      env: TOX_ENV=docs-linkcheck
    - os: osx
      env: TOX_ENV=py26

install:
  - travis_retry ./.travis/install.sh

script:
  - ./.travis/run.sh

after_success:
  - source ~/.venv/bin/activate && coveralls

notifications:
  irc:
     channels: "chat.freenode.net##mimic"
     template:
       - "%{repository}@%{branch} - %{author}: %{message} (%{build_url})"
     use_notice: true

branches:
  only:
    - master
