language: python

env:
  - TOX_ENV=pep8
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=cover
  - TOX_ENV=pypy
  - TOX_ENV=docs
  - TOX_ENV=docs-spellcheck

before_install:
  - if [ "$TOX_ENV" = 'cover' ]; then pip install coveralls; fi

install:
  - ./.travis/install.sh

script: tox -e $TOX_ENV

after_success:
    - if [ "$TOX_ENV" = 'cover' ]; then coveralls; fi

notifications:
  irc:
    channels: "chat.freenode.net##mimic"
    template:
      - "%{repository}@%{branch} - %{author}: %{message} (%{build_url})"
    use_notice: true
