language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install flake8"
  - "pip install pep257==0.3.2"
script:
  # Lint
  - flake8 --max-line-length 105 mimic
  - "pep257 --ignore=D400,D401,D200,D203,D204,D205 mimic"
  # Run tests
  - python -m unittest discover
notifications:
  irc:
    channels: "chat.freenode.net##mimic"
    template:
      - "%{repository}@%{branch} - %{author}: %{message} (%{build_url})"
    use_notice: true
